config/routes.rb
Rails.application.routes.draw do
  resources :solvers

end

app/models/solver.rb
class Solver < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/solvers_controller.rb
class SolversController < ApplicationController
  before_action :set_solver, only: [:show, :edit, :update, :destroy]

  # GET /solvers
  # GET /solvers.json
  def index
    @solvers = Solver.all
  end

  # GET /solvers/1
  # GET /solvers/1.json
  def show
  end

  # GET /solvers/new
  def new
    @solver = Solver.new
  end

  # GET /solvers/1/edit
  def edit
  end

  # POST /solvers
  # POST /solvers.json
  def create
    @solver = Solver.new(solver_params)

    respond_to do |format|
      if @solver.save
        format.html { redirect_to @solver, notice: 'Solver was successfully created.' }
        format.json { render :show, status: :created, location: @solver }
      else
        format.html { render :new }
        format.json { render json: @solver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solvers/1
  # PATCH/PUT /solvers/1.json
  def update
    respond_to do |format|
      if @solver.update(solver_params)
        format.html { redirect_to @solver, notice: 'Solver was successfully updated.' }
        format.json { render :show, status: :ok, location: @solver }
      else
        format.html { render :edit }
        format.json { render json: @solver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solvers/1
  # DELETE /solvers/1.json
  def destroy
    @solver.destroy
    respond_to do |format|
      format.html { redirect_to solvers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solver
      @solver = Solver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solver_params
      params.require(:solver).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/solvers_helper.rb
module SolversHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Remoter</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>'>
<%= yield %>

</body>

</html>

app/views/solvers/_form.html.erb
<%= form_for(@solver) do |f| %>
  <% if @solver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solver.errors.count, "error") %> prohibited this solver from being saved:</h2>

      <ul>
      <% @solver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solvers/edit.html.erb
<h1>Editing solver</h1>

<%= render 'form' %>

<%= link_to 'Show', @solver %> |
<%= link_to 'Back', solvers_path %>

app/views/solvers/index.html.erb
<h1>Listing solvers</h1>

<table>
    <% @solvers.each do |solver| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td class="list_description">
                <dl>
                    <dt><%= solver.title %></dt>
                    <dd><%= truncate(strip_tags(solver.description), length: 80) %></dd>
                </dl>
            </td>
            <td class="list_actions">
            <td><%= link_to 'Show', solver %></td>
            <td><%= link_to 'Edit', edit_solver_path(solver) %></td>
            <td><%= link_to 'Destroy', solver, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </td>
        </tr>
    <% end %>
</table>

<br />

<%= link_to 'New Solver', new_solver_path %>

app/views/solvers/new.html.erb
<h1>New solver</h1>

<%= render 'form' %>

<%= link_to 'Back', solvers_path %>

app/views/solvers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @solver.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @solver.description %>
</p>

<%= link_to 'Edit', edit_solver_path(@solver) %> |
<%= link_to 'Back', solvers_path %>